[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge", "pytorch"]
name = "ML-resources-korean"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
render = "quarto render mybook"

[dependencies]
quarto = ">=1.8.27,<2"
python = ">=3.10"
ipykernel = "*"
pandas = "*"
matplotlib = "*"
seaborn = "*"
scikit-learn = "*"
pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
tensorflow = "*"

